/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.Timer;

/**
 *
 * @author kanishkamadhuranga
 */
public class Add_user extends javax.swing.JFrame implements ActionListener{
    Timer t;
    int i=0;
    /**
     * Creates new form Add_user
     */
    public Add_user() {
        initComponents();
        t= new Timer(100, this);
        loadingBar.setMinimum(0);
        loadingBar.setMaximum(20);
    }
    static String name,nic,email,position,slmcRegNum;
    static JProgressBar staticProgressBar;
    
    public void actionPerformed(ActionEvent e){
        if(i==20){
            if (rows != 0) {
                JOptionPane.showMessageDialog(null, "New User has been sucessfully Added!!!"," Done!!!" ,JOptionPane.INFORMATION_MESSAGE);
                loadingBar.setValue(0);
            } else {
                JOptionPane.showMessageDialog(null, "An Error has Occured"," Error!!!" ,JOptionPane.ERROR_MESSAGE);
                loadingBar.setValue(0);
            }
        }
        i++;
        loadingBar.setValue(i);
    }
    public JProgressBar getLoadingBar(){
        return staticProgressBar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        regNo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        t_nic = new javax.swing.JTextField();
        t_email = new javax.swing.JTextField();
        t_position = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        slmcRegNo = new javax.swing.JTextField();
        loadingBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 40)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Best Care");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 830, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 4.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, 130));

        regNo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        regNo.setText("SLMC Reg. No.");
        jPanel1.add(regNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 170, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 140, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("N.I.C Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 140, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("E-mail address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 140, 30));

        t_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nameActionPerformed(evt);
            }
        });
        jPanel1.add(t_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 480, 30));

        t_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nicActionPerformed(evt);
            }
        });
        jPanel1.add(t_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 480, 30));
        jPanel1.add(t_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 480, 30));

        t_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Admin" }));
        t_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_positionActionPerformed(evt);
            }
        });
        jPanel1.add(t_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 120, 40));

        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 630, 90, 50));

        add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 90, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Position");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 140, 30));

        slmcRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slmcRegNoActionPerformed(evt);
            }
        });
        jPanel1.add(slmcRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 190, 30));
        jPanel1.add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 590, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameActionPerformed

    private void t_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nicActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed
    int rows;
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
//        try {
//            System.out.println("start");
//            
//            DB_Connector.createNewConnection();
//            String name = t_name.getText(), nic_num = t_nic.getText(), e_mail = t_email.getText(), position = (String) t_position.getSelectedItem();
//            String sid = "";
//            if (nic_num.length()!=10) {
//                JOptionPane.showMessageDialog(null, "Incorrect NIC Number\nPlease enter again"," Error!!!" ,JOptionPane.ERROR_MESSAGE);
//                return;
//            }
//            
//            ResultSet rs = null;
//            if (position.equals("Doctor")) {
//                rs = DB_Connector.search("SELECT * FROM Users WHERE position='Doctor'  ");
//            } else {
//                rs = DB_Connector.search("SELECT * FROM Users WHERE position='Admin'  ");
//            }
//            boolean match_found = false;
//            while (rs.next()) {
//                if (rs.getString(1).equals(name)) {
//                    JOptionPane.showMessageDialog(null, "Sorry! the user name you entered already here. Please enter another one");
//                    match_found = true;
//                    break;
//                }
//            }
//            if (match_found) {
//                return;
//            } else {
//                sid = name;
//            }
//
//            Random randomNums = new Random();
//            int rand = (int) (randomNums.nextDouble() * 10000);
//            int password = rand;
//
//            String sql = "INSERT INTO Users VALUES('" + sid + "' , '" + name + "' , '" + e_mail + "' , '" + position + "' , '" + password + "' , '" + nic_num + "')  ";
//            rows = DB_Connector.iud(sql);
//            
//            //progressbar
//            
//            System.out.println("just before");
//            
//            String a, b, x, y;
//            a = "wijesinghekamal7@gmail.com";
//            try {
//                String[] to = {e_mail}; // to - email address.
//                b = "openhereiam7";//password
//                x = "WELCOME!!! Medical Centre - University of Kelaniya";//subject
//                y = "Welcome! "+position+" here is your User Name - "+name+" and Password - "+password+" (please note this is an auto generated password.you are advised to change it on your first log.)";
//                E_mail.sendFromGMail(a, b, to, x, y);
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//            System.out.println("just now sent");
//            
//
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }

        name=t_name.getText();
        nic=t_nic.getText();
        email=t_email.getText();
        position=(String)t_position.getSelectedItem();
        slmcRegNum=slmcRegNo.getText();
        staticProgressBar=loadingBar;

        new ProgressThread().start();
        new AddUserThread().start();
        


    }//GEN-LAST:event_addActionPerformed

    private void t_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_positionActionPerformed
        String selected=(String)t_position.getSelectedItem();
        if(selected.equals("Admin")){
            regNo.setVisible(false);
            slmcRegNo.setVisible(false);
        }else{
            regNo.setVisible(true);
            slmcRegNo.setVisible(true);
        }
    }//GEN-LAST:event_t_positionActionPerformed

    private void slmcRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slmcRegNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slmcRegNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_user().setVisible(true);
            }
        });
    }
    
    public String getName(){
        
        return name;
    }
    public String getNic(){
        return nic;
    }
    public String getEmail(){
        return email;
    }
    public String getPosition(){
        return position;
    }
    public String getSLMC(){
        return slmcRegNum;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel regNo;
    private javax.swing.JTextField slmcRegNo;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_nic;
    private javax.swing.JComboBox<String> t_position;
    // End of variables declaration//GEN-END:variables
}
