/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.Random;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JTextField;

/**
 *
 * @author kanishkamadhuranga
 */
public class LoginFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        
        initComponents();
        jLabel7.setVisible(false);
        jProgressBar1.setVisible(false);
        setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        userpass = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 785));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 490, 310));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Gujarati Sangam MN", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" Best Care");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 330, 70));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setText("Password    :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 180, 40));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("User Name  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 190, 40));

        username.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 310, 40));

        userpass.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel1.add(userpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 310, 40));

        login.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 140, 50));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 210, 20));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel6.setText("Forgot Password");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 110, -1));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 570, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 102));
        jLabel7.setText("Password Resetting");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 626, 170, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 1.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try {
            DB_Connector.createNewConnection();

            String uname = username.getText();
            char[] pass = userpass.getPassword();
            String password = "";
            for (int i = 0; i < pass.length; i++) {
                password += pass[i];
            }
            Home.password=password;
            String sql = "SELECT * FROM Users WHERE uid='" + uname + "' AND password='" + password + "'  ";

            ResultSet rs = DB_Connector.search(sql);

            if (rs.next()) {
                if (rs.getString(4).equals("Doctor")) {
                    Home.Username = rs.getString(2);
                    Home.LoggedDocID=rs.getString(1);                    
                    new Home().setVisible(true);
                    dispose();

                } else {
                    new admin().setVisible(true);
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect Username or Password!\n\tTRY AGAIN");

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_loginActionPerformed

    static String UName="";
    static JLabel jl=null;
    static JProgressBar JProgressBar;
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
//        jLabel6.setBackground(Color.red);
//        String a, b, x, y;
//        a = "wijesinghekamal7@gmail.com";
//        String sql = "SELECT * FROM Users Where uid='" + username.getText() + "'  ";
//        ResultSet rs=null;
//        try {
//            DB_Connector.createNewConnection();
//             rs = DB_Connector.search(sql);
//             rs.next();
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
//        
//        
//        Random randomNums = new Random();
//        int rand = (int) (randomNums.nextDouble() * 10000);
//        int password = rand;
//        
//        sql="UPDATE Users SET password='"+password+"' WHERE uid='"+username.getText()+"'  ";
//        try {
//            DB_Connector.createNewConnection();
//            int row=DB_Connector.iud(sql);
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
//        
//        try{
//            String[] to = {rs.getString(3)}; // to - email address.
//            b = "openhereiam7";//password
//            x = "Medical Centre - University of Kelaniya Password Reset";//subject
//            y = "Welcome! Your Password was sucessfully recovered. This is your new Password "+password+" \nThis is an auto generated password.You are adviced to change it after login.\n Thank You.";
//            E_mail.sendFromGMail(a, b, to, x, y);
//            JOptionPane.showMessageDialog(null, "Your password has been sucessfully recovered.\nCheck your e-mail for new password!!!"," Done!!!" ,JOptionPane.INFORMATION_MESSAGE);
//        }catch(Exception e){
//            e.printStackTrace();
//        }    
//        jLabel6.setBackground(Color.GREEN);
        jLabel7.setVisible(true);
        jProgressBar1.setVisible(true);
        JProgressBar=jProgressBar1;
        System.out.println("before");
        jl=jLabel6;
        
        UName=username.getText();
        
        new RecoveryEmailThread().start();
        new ProgressThread2().start();
        System.out.println("after");
    }//GEN-LAST:event_jLabel6MouseClicked

    public JProgressBar getLoadingBar(){
        return LoginFrame.JProgressBar;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton login;
    private javax.swing.JTextField username;
    private javax.swing.JPasswordField userpass;
    // End of variables declaration//GEN-END:variables
}
